gSongTable:: @ 84A32CC

	/* 0 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song se_pc_login, 1, 1
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song se_select, 2, 2
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song se_pin, 1, 1
	song se_boo, 1, 1
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 25 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song se_ball_bounce_1, 1, 1

	/* 50 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song se_ding_dong, 1, 1
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 75 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 100 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song se_pokenav_on, 1, 1
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 125 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 150 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 175 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 200 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 225 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 250 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_heal, 2, 2
	song mus_level_up, 2, 2
	song mus_obtain_item, 2, 2
	song mus_evolved, 2, 2

	song mus_obtain_badge, 2, 2
	song mus_obtain_tmhm, 2, 2
	song mus_obtain_berry, 2, 2
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_slots_jackpot, 2, 2
	song mus_slots_win, 2, 2

	song mus_move_deleted, 2, 2
	song mus_too_bad, 2, 2
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 275 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 300 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dex_rating, 2, 2
	song mus_obtain_key_item, 2, 2
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 325 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_mystery_gift, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_poke_flute, 2, 2
	song mus_dummy, 0, 0

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

	/* 345 */

	song mus_dummy, 0, 0
	song mus_dummy, 0, 0

dummy_song_header: @ 84A3DA4
	.byte 0, 0, 0, 0

/*
  0 mus_dummy
  2 se_pc_login
  5 se_select
  7 se_wall_hit
 21 se_pin

 22 se_boo
 49 se_ball_bounce_1
 66 se_ding_dong
103 se_pokenav_on
256 mus_heal

257 mus_level_up
258 mus_obtain_item
259 mus_evolved
260 mus_obtain_badge
261 mus_obtain_tmhm

262 mus_obtain_berry
268 mus_slots_jackpot
269 mus_slots_win
270 mus_move_deleted
271 mus_too_bad

317 mus_dex_rating
318 mus_obtain_key_item
329 mus_mystery_gift
338 mus_poke_flute
*/
