const struct mevent_client_cmd custom_sharedClientScript_SendVersion[] = {
	CLIENT_BEGIN_SENDING_CLIENT_VERSION,
	CLIENT_WAIT_FOR_SEND_TO_FINISH,
	CLIENT_WAIT_FOR_RECEIVE_WITH_MAGIC_NUMBER(MAGIC_CLIENT_COMMANDS),
	CLIENT_EXECUTE_COMMANDS_FROM_SERVER
};

const struct mevent_client_cmd custom_sharedClientScript_Incompatible[] = {
	CLIENT_BEGIN_SENDING_ENTIRE_BUFFER_AND_WAIT,
	CLIENT_RETURN(RETURN_INCOMPATIBLE)
};

//===============//

const struct mevent_server_cmd custom_sharedServerScript_GetVersion[] = {
	SERVER_BEGIN_SENDING_CLIENT_COMMANDS_WITH_SIZE_AT(4*CLIENT_COMMAND_SIZE, custom_sharedClientScript_SendVersion),
	SERVER_WAIT_FOR_SEND_TO_FINISH,
	SERVER_WAIT_FOR_RECEIVE_WITH_MAGIC_NUMBER(MAGIC_CLIENT_VERSION),
	SERVER_PREPARE_TO_GET_CLIENT_VERSION,
	SERVER_GET_CLIENT_VERSION,
	SERVER_BRANCH_TO_CALLBACK
};

const struct mevent_server_cmd custom_sharedServerScript_Incompatible[] = {
	SERVER_BEGIN_SENDING_CLIENT_COMMANDS_WITH_SIZE_AT(2*CLIENT_COMMAND_SIZE, custom_sharedClientScript_Incompatible),
	SERVER_WAIT_FOR_SEND_TO_FINISH,
	SERVER_WAIT_FOR_RECEIVE_WITH_MAGIC_NUMBER(MAGIC_CLIENT_SENT_BUFFER),
	SERVER_RETURN(RETURN_INCOMPATIBLE)
};
