void AnimateElevator(void){}
void AnimatePcTurnOff(void){}
void AnimatePcTurnOn(void){}
void AnimateTeleporterCable(void){}
void AnimateTeleporterHousing(void){}
void AreLeadMonEVsMaxedOut(void){}
void AwardBattleTowerRibbons(void){}
void BackupHelpContext(void){}
void BattleCardAction(void){}
void BattleTowerMapScript2(void){}
void BattleTower_SoftReset(void){}
void BattleTowerUtil(void){}
void BedroomPC(void){}
void BrailleCursorToggle(void){}
void BufferBigGuyOrBigGirlString(void){}
void BufferEReaderTrainerGreeting(void){}
void BufferEReaderTrainerName(void){}
void BufferMonNickname(void){}
void BufferMoveDeleterNicknameAndMove(void){}
void BufferRandomHobbyOrLifestyleString(void){}
void BufferSonOrDaughterString(void){}
void BufferTMHMMoveName(void){}
void BufferUnionRoomPlayerName(void){}
void CableClub_AskSaveTheGame(void){}
void CalculatePlayerPartyCount(void){}
void CallTrainerTowerFunc(void){}
void CapeBrinkGetMoveToTeachLeadPokemon(void){}
void ChangeBoxPokemonNickname(void){}
void ChangePokemonNickname(void){}
void CheckAddCoins(void){}
void CheckPartyBattleTowerBanlist(void){}
void ChooseBattleTowerPlayerParty(void){}
void ChooseHalfPartyForBattle(void){}
void ChooseMonForMoveTutor(void){}
void ChooseMonForWirelessMinigame(void){}
void ChooseNextBattleTowerTrainer(void){}
void ChoosePartyMon(void){}
void ChooseSendDaycareMon(void){}
void CleanupLinkRoomState(void){}
void CloseElevatorCurrentFloorWindow(void){}
void CloseMuseumFossilPic(void){}
void CompareHeracrossSize(void){}
void CompareMagikarpSize(void){}
void CountPartyAliveNonEggMons_IgnoreVar0x8004Slot(void){}
void CountPartyNonEggMons(void){}
void CreateEventLegalEnemyMon(void){}
void CreateInGameTradePokemon(void){}
void CreatePCMenu(void){}
void DaisyMassageServices(void){}
void DaycareMonReceivedMail(void){}
void DetermineBattleTowerPrize(void){}
void DisplayBerryPowderVendorMenu(void){}
void DisplayMoveTutorMenu(void){}
void DoCableClubWarp(void){}
void DoCredits(void){}
void DoDeoxysTriangleInteraction(void){}
void DoDiveWarp(void){}
void DoesPartyHaveEnigmaBerry(void){}
void DoesPlayerPartyContainSpecies(void){}
void DoFallWarp(void){}
void DoInGameTradeScene(void){}
void DoPicboxCancel(void){}
void DoPokemonLeagueLightingEffect(void){}
void DoSeagallopFerryScene(void){}
void DoSSAnneDepartureCutscene(void){}
void DoWateringBerryTreeAnim(void){}
void DrawElevatorCurrentFloorWindow(void){}
void DrawSeagallopDestinationMenu(void){}
void DrawWholeMapView(void){}
void Dummy_TryEnableBravoTrainerBattleTower(void){}
void EggHatch(void){}
void EndTrainerApproach(void){}
void EnterColosseumPlayerSpot(void){}
void EnterHallOfFame(void){}
void EnterSafariMode(void){}
void EnterTradeSeat(void){}
void ExitLinkRoom(void){}
void ExitSafariMode(void){}
void Field_AskSaveTheGame(void){}
void ForcePlayerOntoBike(void){}
void ForcePlayerToStartSurfing(void){}
void GetBattleOutcome(void){}
void GetCostToWithdrawRoute5DaycareMon(void){}
void GetDaycareCost(void){}
void GetDaycareMonNicknames(void){}
void GetDaycarePokemonCount(void){}
void GetDaycareState(void){}
void GetElevatorFloor(void){}
void GetHeracrossSizeRecordInfo(void){}
void GetInGameTradeSpeciesInfo(void){}
void GetLeadMonFriendship(void){}
void GetMagikarpSizeRecordInfo(void){}
void GetMartClerkObjectId(void){}
void GetNumLevelsGainedForRoute5DaycareMon(void){}
void GetNumLevelsGainedFromDaycare(void){}
void GetNumMovesSelectedMonHas(void){}
void GetPartyMonSpecies(void){}
void GetPCBoxToSendMon(void){}
void GetPlayerAvatarBike(void){}
void GetPlayerFacingDirection(void){}
void GetPlayerTrainerIdOnesDigit(void){}
void GetPlayerXY(void){}
void GetPokedexCount(void){}
void GetProfOaksRatingMessage(void){}
void GetQuestLogState(void){}
void GetRandomSlotMachineId(void){}
void GetSeagallopNumber(void){}
void GetSelectedMonNicknameAndSpecies(void){}
void GetSelectedSeagallopDestination(void){}
void GetStarterSpecies(void){}
void GetTradeSpecies(void){}
void GetTrainerBattleMode(void){}
void GiveBattleTowerPrize(void){}
void GiveEggFromDaycare(void){}
void GiveLeadMonEffortRibbon(void){}
void HallOfFamePCBeginFade(void){}
void HasAllKantoMons(void){}
void HasAllMons(void){}
void HasAtLeastOneBerry(void){}
void HasEnoughMonsForDoubleBattle(void){}
void HasLeadMonBeenRenamed(void){}
void HasLearnedAllMovesFromCapeBrinkTutor(void){}
void HealPlayerParty(void){}
void HelpSystem_Disable(void){}
void HelpSystem_Enable(void){}
void InitElevatorFloorSelectMenuPos(void){}
void InitRoamer(void){}
void InitUnionRoom(void){}
void IsBadEggInParty(void){}
void IsDodrioInParty(void){}
void IsMonOTIDNotPlayers(void){}
void IsMonOTNameNotPlayers(void){}
void IsPlayerLeftOfVermilionSailor(void){}
void IsPlayerNotInTrainerTowerLobby(void){}
void IsPokemonJumpSpeciesInParty(void){}
void IsPokerusInParty(void){}
void IsSelectedMonEgg(void){}
void IsStarterFirstStageInParty(void){}
void IsThereMonInRoute5Daycare(void){}
void IsThereRoomInAnyBoxForMorePokemon(void){}
void IsTrainerReadyForRematch(void){}
void LeadMonHasEffortRibbon(void){}
void ListMenu(void){}
void LookThroughPorthole(void){}
void LoopWingFlapSound(void){}
void MoveDeleterForgetMove(void){}
void NameRaterWasNicknameChanged(void){}
void NullFieldSpecial(void){}
void OpenMuseumFossilPic(void){}
void Overworld_PlaySpecialMapMusic(void){}
void OverworldWhiteOutGetMoneyLoss(void){}
void PlayerHasGrassPokemonInParty(void){}
void PlayerPartyContainsSpeciesWithPlayerID(void){}
void PlayerPC(void){}
void PlayTrainerEncounterMusic(void){}
void PrintBattleTowerTrainerGreeting(void){}
void PrintPlayerBerryPowderAmount(void){}
void PutMonInRoute5Daycare(void){}
void QuestLog_CutRecording(void){}
void QuestLog_StartRecordingInputsAfterDeferredEvent(void){}
void ReducePlayerPartyToThree(void){}
void RegisteredItemHandleBikeSwap(void){}
void RejectEggFromDayCare(void){}
void RemoveBerryPowderVendorMenu(void){}
void RemoveCameraObject(void){}
void RestoreHelpContext(void){}
void ReturnFromLinkRoom(void){}
void ReturnToListMenu(void){}
void RockSmashWildEncounter(void){}
void SampleResortGorgeousMonAndReward(void){}
void SaveBattleTowerProgress(void){}
void Script_BufferFanClubTrainerName(void){}
void Script_ClearHeldMovement(void){}
void Script_FacePlayer(void){}
void Script_FadeOutMapMusic(void){}
void Script_GetNumFansOfPlayerInTrainerFanClub(void){}
void Script_HasEnoughBerryPowder(void){}
void Script_HasTrainerBeenFought(void){}
void ScriptHatchMon(void){}
void Script_IsFanClubMemberFanOfPlayer(void){}
void Script_ResetUnionRoomTrade(void){}
void Script_SetHelpContext(void){}
void Script_SetPlayerGotFirstFans(void){}
void Script_ShowLinkTrainerCard(void){}
void Script_TakeBerryPowder(void){}
void Script_TryGainNewFanFromCounter(void){}
void Script_TryLoseFansFromPlayTimeAfterLinkBattle(void){}
void Script_TryLoseFansFromPlayTime(void){}
void Script_UpdateTrainerFanClubGameClear(void){}
void SeafoamIslandsB4F_CurrentDumpsPlayerOnLand(void){}
void SelectMoveDeleterMove(void){}
void SelectMoveTutorMon(void){}
void SetBattledTrainerFlag(void){}
void SetBattleTowerParty(void){}
void SetBattleTowerProperty(void){}
void SetCableClubWarp(void){}
void SetCB2WhiteOut(void){}
void SetDaycareCompatibilityString(void){}
void SetDeoxysTrianglePalette(void){}
void SetEReaderTrainerGfxId(void){}
void SetFlavorTextFlagFromSpecialVars(void){}
void SetHelpContextForMap(void){}
void SetHiddenItemFlag(void){}
void SetIcefallCaveCrackedIceMetatiles(void){}
void SetSeenMon(void){}
void SetUpTrainerMovement(void){}
void SetUsedPkmnCenterQuestLogEvent(void){}
void SetVermilionTrashCans(void){}
void ShakeScreen(void){}
void ShouldShowBoxWasFullMessage(void){}
void ShouldTryRematchBattle(void){}
void ShowBattleRecords(void){}
void ShowBerryCrushRankings(void){}
void ShowDaycareLevelMenu(void){}
void ShowDiploma(void){}
void ShowDodrioBerryPickingRecords(void){}
void ShowEasyChatMessage(void){}
void ShowEasyChatScreen(void){}
void ShowFieldMessageStringVar4(void){}
void ShowPokemonJumpRecords(void){}
void ShowPokemonStorageSystemPC(void){}
void ShowTownMap(void){}
void ShowTrainerCantBattleSpeech(void){}
void ShowTrainerIntroSpeech(void){}
void ShowWirelessCommunicationScreen(void){}
void SpawnCameraObject(void){}
void StartDroughtWeatherBlend(void){}
void StartGroudonKyogreBattle(void){}
void StartLegendaryBattle(void){}
void StartMarowakBattle(void){}
void StartOldManTutorialBattle(void){}
void StartRegiBattle(void){}
void StartRematchBattle(void){}
void StartSouthernIslandBattle(void){}
void StartSpecialBattle(void){}
void StartWiredCableClubTrade(void){}
void StickerManGetBragFlags(void){}
void StoreSelectedPokemonInDaycare(void){}
void TakePokemonFromDaycare(void){}
void TakePokemonFromRoute5Daycare(void){}
void TryBattleLinkup(void){}
void TryBecomeLinkLeader(void){}
void TryContestLinkup(void){}
void TryFieldPoisonWhiteOut(void){}
void TryJoinLinkGroup(void){}
void TryRecordMixLinkup(void){}
void TryTradeLinkup(void){}
void UnionRoomSpecial(void){}
void UpdateLoreleiDollCollection(void){}
void UpdatePickStateFromSpecialVar8005(void){}
void UpdateTrainerCardPhotoIcons(void){}
void VsSeekerFreezeObjectsAfterChargeComplete(void){}
void VsSeekerResetObjectMovementAfterChargeComplete(void){}
void LoadPlayerBag(void){}
void SetPostgameFlags(void){}
void SetUnlockedPokedexFlags(void){}
void SavePlayerParty(void){}
void LoadPlayerParty(void){}
void ReadTrainerTowerAndValidate(void){}
void IsEnoughForCostInVar0x8005(void){}
void SubtractMoneyFromVar0x8005(void){}
