//[[!!!]]
// decoration.c
#include "global.h"
#include "decoration.h"
#include "constants/decorations.h"
#include "data/decoration/tiles.h"
#include "data/decoration/description.h"
#include "data/decoration/header.h"

// battle_records.h
#include "battle_records.h"
void TryRecordLinkBattleOutcome(s32 battlerId){}

// specials
void BackupHelpContext(void){}
void CallTrainerTowerFunc(void){}
void ChooseMonForWirelessMinigame(void){}
void CompareHeracrossSize(void){}
void CompareMagikarpSize(void){}
void CreateInGameTradePokemon(void){}
void DoCredits(void){}
void DoInGameTradeScene(void){}
void DoPokemonLeagueLightingEffect(void){}
void DoSeagallopFerryScene(void){}
void DoSSAnneDepartureCutscene(void){}
void DoWateringBerryTreeAnim(void){}
void DrawElevatorCurrentFloorWindow(void){}
void EnterHallOfFame(void){}
void GetElevatorFloor(void){}
void GetHeracrossSizeRecordInfo(void){}
void GetInGameTradeSpeciesInfo(void){}
void GetMagikarpSizeRecordInfo(void){}
void GetQuestLogState(void){}
void GetSeagallopNumber(void){}
void GetTradeSpecies(void){}
void HelpSystem_Disable(void){}
void HelpSystem_Enable(void){}
void InitElevatorFloorSelectMenuPos(void){}
void InitRoamer(void){}
void IsDodrioInParty(void){}
void IsPlayerLeftOfVermilionSailor(void){}
void IsPlayerNotInTrainerTowerLobby(void){}
void IsPokemonJumpSpeciesInParty(void){}
void IsTrainerReadyForRematch(void){}
void LookThroughPorthole(void){}
void QuestLog_CutRecording(void){}
void QuestLog_StartRecordingInputsAfterDeferredEvent(void){}
void RestoreHelpContext(void){}
void Script_SetHelpContext(void){}
void SeafoamIslandsB4F_CurrentDumpsPlayerOnLand(void){}
void SetCB2WhiteOut(void){}
void SetHelpContextForMap(void){}
void SetUsedPkmnCenterQuestLogEvent(void){}
void ShouldTryRematchBattle(void){}
void ShowBattleRecords(void){}
void ShowBerryCrushRankings(void){}
void ShowDiploma(void){}
void ShowDodrioBerryPickingRecords(void){}
void ShowPokemonJumpRecords(void){}
void VsSeekerFreezeObjectsAfterChargeComplete(void){}
void VsSeekerResetObjectMovementAfterChargeComplete(void){}

